package ws.owl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WebServiceDelegate", targetNamespace = "http://owl.ws/")
public interface WebServiceDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns ws.owl.ResourceData
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDomain", targetNamespace = "http://owl.ws/", className = "ws.owl.GetDomain")
	@ResponseWrapper(localName = "getDomainResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetDomainResponse")
	public ResourceData getDomain(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<ws.owl.PropertyData>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "listProperties", targetNamespace = "http://owl.ws/", className = "ws.owl.ListProperties")
	@ResponseWrapper(localName = "listPropertiesResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.ListPropertiesResponse")
	public List<PropertyData> listProperties(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns ws.owl.Message
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "removeUser", targetNamespace = "http://owl.ws/", className = "ws.owl.RemoveUser")
	@ResponseWrapper(localName = "removeUserResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.RemoveUserResponse")
	public Message removeUser(@WebParam(name = "arg0", targetNamespace = "")
	String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "createInstance", targetNamespace = "http://owl.ws/", className = "ws.owl.CreateInstance")
	@ResponseWrapper(localName = "createInstanceResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.CreateInstanceResponse")
	public boolean createInstance(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			String arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 */
	@WebMethod
	@RequestWrapper(localName = "removeCodeIndividual", targetNamespace = "http://owl.ws/", className = "ws.owl.RemoveCodeIndividual")
	@ResponseWrapper(localName = "removeCodeIndividualResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.RemoveCodeIndividualResponse")
	public void removeCodeIndividual(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			Boolean arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns ws.owl.Message
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "backupOWL", targetNamespace = "http://owl.ws/", className = "ws.owl.BackupOWL")
	@ResponseWrapper(localName = "backupOWLResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.BackupOWLResponse")
	public Message backupOWL(@WebParam(name = "arg0", targetNamespace = "")
	String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "isInitited", targetNamespace = "http://owl.ws/", className = "ws.owl.IsInitited")
	@ResponseWrapper(localName = "isInititedResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.IsInititedResponse")
	public boolean isInitited(@WebParam(name = "arg0", targetNamespace = "")
	String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "reloadOntology", targetNamespace = "http://owl.ws/", className = "ws.owl.ReloadOntology")
	@ResponseWrapper(localName = "reloadOntologyResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.ReloadOntologyResponse")
	public boolean reloadOntology(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @return returns ws.owl.ShareData
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getShareData", targetNamespace = "http://owl.ws/", className = "ws.owl.GetShareData")
	@ResponseWrapper(localName = "getShareDataResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetShareDataResponse")
	public ShareData getShareData();

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "listClassInstance", targetNamespace = "http://owl.ws/", className = "ws.owl.ListClassInstance")
	@ResponseWrapper(localName = "listClassInstanceResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.ListClassInstanceResponse")
	public List<String> listClassInstance(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "listAllRelatedInstance", targetNamespace = "http://owl.ws/", className = "ws.owl.ListAllRelatedInstance")
	@ResponseWrapper(localName = "listAllRelatedInstanceResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.ListAllRelatedInstanceResponse")
	public List<String> listAllRelatedInstance(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<ws.owl.PropertyData>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAllClassProperties", targetNamespace = "http://owl.ws/", className = "ws.owl.GetAllClassProperties")
	@ResponseWrapper(localName = "getAllClassPropertiesResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetAllClassPropertiesResponse")
	public List<PropertyData> getAllClassProperties(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns java.util.List<ws.owl.ClassData>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSubClasses", targetNamespace = "http://owl.ws/", className = "ws.owl.GetSubClasses")
	@ResponseWrapper(localName = "getSubClassesResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetSubClassesResponse")
	public List<ClassData> getSubClasses(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			Boolean arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<ws.owl.ClassData>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSuperClasses", targetNamespace = "http://owl.ws/", className = "ws.owl.GetSuperClasses")
	@ResponseWrapper(localName = "getSuperClassesResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetSuperClassesResponse")
	public List<ClassData> getSuperClasses(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getPropertySpecificDataType", targetNamespace = "http://owl.ws/", className = "ws.owl.GetPropertySpecificDataType")
	@ResponseWrapper(localName = "getPropertySpecificDataTypeResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetPropertySpecificDataTypeResponse")
	public String getPropertySpecificDataType(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getObjectPropertyRanges", targetNamespace = "http://owl.ws/", className = "ws.owl.GetObjectPropertyRanges")
	@ResponseWrapper(localName = "getObjectPropertyRangesResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetObjectPropertyRangesResponse")
	public List<String> getObjectPropertyRanges(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getObjectPropertyDomains", targetNamespace = "http://owl.ws/", className = "ws.owl.GetObjectPropertyDomains")
	@ResponseWrapper(localName = "getObjectPropertyDomainsResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetObjectPropertyDomainsResponse")
	public List<String> getObjectPropertyDomains(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<ws.owl.PropertyData>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSubProperties", targetNamespace = "http://owl.ws/", className = "ws.owl.GetSubProperties")
	@ResponseWrapper(localName = "getSubPropertiesResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetSubPropertiesResponse")
	public List<PropertyData> getSubProperties(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<ws.owl.PropertyData>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSuperProperties", targetNamespace = "http://owl.ws/", className = "ws.owl.GetSuperProperties")
	@ResponseWrapper(localName = "getSuperPropertiesResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetSuperPropertiesResponse")
	public List<PropertyData> getSuperProperties(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<ws.owl.ClassData>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "listClasses", targetNamespace = "http://owl.ws/", className = "ws.owl.ListClasses")
	@ResponseWrapper(localName = "listClassesResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.ListClassesResponse")
	public List<ClassData> listClasses(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "writeToOWL", targetNamespace = "http://owl.ws/", className = "ws.owl.WriteToOWL")
	@ResponseWrapper(localName = "writeToOWLResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.WriteToOWLResponse")
	public void writeToOWL(@WebParam(name = "arg0", targetNamespace = "")
	String arg0, @WebParam(name = "arg1", targetNamespace = "")
	String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "saveDocumentToOWL", targetNamespace = "http://owl.ws/", className = "ws.owl.SaveDocumentToOWL")
	@ResponseWrapper(localName = "saveDocumentToOWLResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.SaveDocumentToOWLResponse")
	public void saveDocumentToOWL(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns ws.owl.ClassData
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getClassByName", targetNamespace = "http://owl.ws/", className = "ws.owl.GetClassByName")
	@ResponseWrapper(localName = "getClassByNameResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetClassByNameResponse")
	public ClassData getClassByName(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns ws.owl.ClassData
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getClassByShortName", targetNamespace = "http://owl.ws/", className = "ws.owl.GetClassByShortName")
	@ResponseWrapper(localName = "getClassByShortNameResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetClassByShortNameResponse")
	public ClassData getClassByShortName(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns ws.owl.PropertyData
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getPropertyByName", targetNamespace = "http://owl.ws/", className = "ws.owl.GetPropertyByName")
	@ResponseWrapper(localName = "getPropertyByNameResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetPropertyByNameResponse")
	public PropertyData getPropertyByName(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns ws.owl.PropertyData
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getPropertyByShortName", targetNamespace = "http://owl.ws/", className = "ws.owl.GetPropertyByShortName")
	@ResponseWrapper(localName = "getPropertyByShortNameResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetPropertyByShortNameResponse")
	public PropertyData getPropertyByShortName(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "checkExistIndividual", targetNamespace = "http://owl.ws/", className = "ws.owl.CheckExistIndividual")
	@ResponseWrapper(localName = "checkExistIndividualResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.CheckExistIndividualResponse")
	public Boolean checkExistIndividual(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns ws.owl.IndividualData
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getIndividualByName", targetNamespace = "http://owl.ws/", className = "ws.owl.GetIndividualByName")
	@ResponseWrapper(localName = "getIndividualByNameResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetIndividualByNameResponse")
	public IndividualData getIndividualByName(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns ws.owl.IndividualData
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getIndividualByShortName", targetNamespace = "http://owl.ws/", className = "ws.owl.GetIndividualByShortName")
	@ResponseWrapper(localName = "getIndividualByShortNameResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetIndividualByShortNameResponse")
	public IndividualData getIndividualByShortName(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg3
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 */
	@WebMethod
	@RequestWrapper(localName = "addDatatypeProperty", targetNamespace = "http://owl.ws/", className = "ws.owl.AddDatatypeProperty")
	@ResponseWrapper(localName = "addDatatypePropertyResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.AddDatatypePropertyResponse")
	public void addDatatypeProperty(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			String arg2, @WebParam(name = "arg3", targetNamespace = "")
			String arg3);

	/**
	 * 
	 * @param arg3
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 */
	@WebMethod
	@RequestWrapper(localName = "addObjectProperty", targetNamespace = "http://owl.ws/", className = "ws.owl.AddObjectProperty")
	@ResponseWrapper(localName = "addObjectPropertyResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.AddObjectPropertyResponse")
	public void addObjectProperty(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			String arg2, @WebParam(name = "arg3", targetNamespace = "")
			String arg3);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<ws.owl.ArrayListData>
	 */
	@WebMethod(operationName = "SparqlResultList")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "SparqlResultList", targetNamespace = "http://owl.ws/", className = "ws.owl.SparqlResultList")
	@ResponseWrapper(localName = "SparqlResultListResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.SparqlResultListResponse")
	public List<ArrayListData> sparqlResultList(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns ws.owl.QueryData
	 */
	@WebMethod(operationName = "SparqlResultMap")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "SparqlResultMap", targetNamespace = "http://owl.ws/", className = "ws.owl.SparqlResultMap")
	@ResponseWrapper(localName = "SparqlResultMapResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.SparqlResultMapResponse")
	public QueryData sparqlResultMap(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getValueOfSpecificPropertyForIndividual", targetNamespace = "http://owl.ws/", className = "ws.owl.GetValueOfSpecificPropertyForIndividual")
	@ResponseWrapper(localName = "getValueOfSpecificPropertyForIndividualResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetValueOfSpecificPropertyForIndividualResponse")
	public List<String> getValueOfSpecificPropertyForIndividual(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			String arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<ws.owl.BkIndividualProperty>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getValuesOfIndividual", targetNamespace = "http://owl.ws/", className = "ws.owl.GetValuesOfIndividual")
	@ResponseWrapper(localName = "getValuesOfIndividualResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetValuesOfIndividualResponse")
	public List<BkIndividualProperty> getValuesOfIndividual(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 */
	@WebMethod
	@RequestWrapper(localName = "saveValuesOfIndividual", targetNamespace = "http://owl.ws/", className = "ws.owl.SaveValuesOfIndividual")
	@ResponseWrapper(localName = "saveValuesOfIndividualResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.SaveValuesOfIndividualResponse")
	public void saveValuesOfIndividual(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			List<InstanceData> arg1,
			@WebParam(name = "arg2", targetNamespace = "")
			Boolean arg2);

	/**
	 * 
	 * @param arg3
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 */
	@WebMethod
	@RequestWrapper(localName = "addLabelForResource", targetNamespace = "http://owl.ws/", className = "ws.owl.AddLabelForResource")
	@ResponseWrapper(localName = "addLabelForResourceResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.AddLabelForResourceResponse")
	public void addLabelForResource(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			LanguageEnum arg2, @WebParam(name = "arg3", targetNamespace = "")
			String arg3);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getLabelFromResource", targetNamespace = "http://owl.ws/", className = "ws.owl.GetLabelFromResource")
	@ResponseWrapper(localName = "getLabelFromResourceResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetLabelFromResourceResponse")
	public String getLabelFromResource(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			LanguageEnum arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "removeIndividual", targetNamespace = "http://owl.ws/", className = "ws.owl.RemoveIndividual")
	@ResponseWrapper(localName = "removeIndividualResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.RemoveIndividualResponse")
	public void removeIndividual(@WebParam(name = "arg0", targetNamespace = "")
	String arg0, @WebParam(name = "arg1", targetNamespace = "")
	String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getClassOfIndividual", targetNamespace = "http://owl.ws/", className = "ws.owl.GetClassOfIndividual")
	@ResponseWrapper(localName = "getClassOfIndividualResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetClassOfIndividualResponse")
	public String getClassOfIndividual(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns ws.owl.DocumentSaveData
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDocumentSaveData", targetNamespace = "http://owl.ws/", className = "ws.owl.GetDocumentSaveData")
	@ResponseWrapper(localName = "getDocumentSaveDataResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetDocumentSaveDataResponse")
	public DocumentSaveData getDocumentSaveData(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getPropertiesOfClassByRange", targetNamespace = "http://owl.ws/", className = "ws.owl.GetPropertiesOfClassByRange")
	@ResponseWrapper(localName = "getPropertiesOfClassByRangeResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.GetPropertiesOfClassByRangeResponse")
	public List<String> getPropertiesOfClassByRange(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			String arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns ws.owl.Message
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "validateUser", targetNamespace = "http://owl.ws/", className = "ws.owl.ValidateUser")
	@ResponseWrapper(localName = "validateUserResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.ValidateUserResponse")
	public Message validateUser(@WebParam(name = "arg0", targetNamespace = "")
	String arg0, @WebParam(name = "arg1", targetNamespace = "")
	String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns ws.owl.Message
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "addUser", targetNamespace = "http://owl.ws/", className = "ws.owl.AddUser")
	@ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.AddUserResponse")
	public Message addUser(@WebParam(name = "arg0", targetNamespace = "")
	String arg0, @WebParam(name = "arg1", targetNamespace = "")
	String arg1, @WebParam(name = "arg2", targetNamespace = "")
	String arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns ws.owl.Message
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "changePassword", targetNamespace = "http://owl.ws/", className = "ws.owl.ChangePassword")
	@ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://owl.ws/", className = "ws.owl.ChangePasswordResponse")
	public Message changePassword(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			String arg2);

}
