package ws.data;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DataServiceService service = new DataServiceService();
 * DataServiceDelegate portType = service.getDataServicePort();
 * portType.isInitited(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DataServiceService", targetNamespace = "http://data.ws/", wsdlLocation = "http://dattt-pc:8080/SEService/DataServicePort?WSDL")
public class DataServiceService extends Service {

	private final static URL DATASERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(ws.data.DataServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = ws.data.DataServiceService.class.getResource(".");
			url = new URL(baseUrl,
					"http://dattt-pc:8080/SEService/DataServicePort?WSDL");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://dattt-pc:8080/SEService/DataServicePort?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DATASERVICESERVICE_WSDL_LOCATION = url;
	}

	public DataServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DataServiceService() {
		super(DATASERVICESERVICE_WSDL_LOCATION, new QName("http://data.ws/",
				"DataServiceService"));
	}

	/**
	 * 
	 * @return returns DataServiceDelegate
	 */
	@WebEndpoint(name = "DataServicePort")
	public DataServiceDelegate getDataServicePort() {
		return super.getPort(new QName("http://data.ws/", "DataServicePort"),
				DataServiceDelegate.class);
	}

}
